language: ruby
rvm:
  - 2.4.1
before_script:
  - cp config/database.travis.yml config/database.yml
  - psql -c 'create database flashcards_advanced_test;' -U postgres
  - bundle exec rake db:test:prepare --trace
  - bundle exec rake db:test:load --trace
script:
  - RAILS_ENV=test bundle exec rake spec